Server:
  KeyID: notification-cluster0
  Name: "Notification service"
  APIKey: f7ed9e0aff0833a0b9a80ca94708faf7
  AppVersion: 1.0.0
  BaseURI: 127.0.0.1:5050
  RestAPIPort: :5050
  GrpcPort: :6050
  DebugMode: false
  ReadTimeout: 5s
  WriteTimeout: 5s
  SSL: true
  CtxDefaultTimeout: 5
  ExpirationLimitTime: 30s

DB:
  Mongodb:
    Connection: mongodb://localhost:27017
    DbName: latipe-notification-db
    Username: root
    Password: 123123
    ConnectTimeout: 10
    MaxConnIdleTime:
    MinPoolSize:
    MaxPoolSize: 20

Cache:
  Redis:
    Address: localhost
    Port: 6379
    Password:
    DB: 9

RabbitMQ:
  ServiceName: notify_service
  Connection: amqp://guest:guest@localhost:5672/
  ConsumerName: notification_service
  ProducerName: notification_service

  NotificationExchange: notify_exchange
  SendMessageRoutingKey: notify.send


AdapterService:
  AuthService:
    BaseURL: http://localhost:8081
    InternalKey:
  UserService:
    UserURL: http://localhost:8181
    InternalKey:

GRPC:
  APIKey: 123456

Firebase:
  ServiceAccountKeyFilePath: config/firebase-service-account.json

GrpcInfrastructure:
  ScheduleGRPC:
    Connection: localhost:9665
    CallbackURL: http://localhost:5050/api/v1/notifications/schedule/callback
    APIGrpcKey: "Z6/gWGXJQMl9iVFDepzPbP6Y9wBnfq1FU2tgKu46KWRdm9Mkc1Ub4irkGQzN7ohbWLMAsL/46gG6dll9xx+oqg=="